### ISSUE TITLE
Webpage.

### ISSUE THREAD

**Issue by reveurguy** [reveurguy/Color-Game#1]
I want to host this simple game on a webpage.

**Comment by ShubhamPalriwala** [comment]
Can you please elaborate exactly on what youre looking for?
Because I think this a client side webpage thus it shouldn't be a problem hosting it.

**Comment by magnusp** [comment]
A neat way to host is with https://pages.github.com. Would that be a good option for you?

**Comment by reveurguy** [comment]
yeah, i'll check that @magnusp

**Comment by ShubhamPalriwala** [comment]
> A neat way to host is with https://pages.github.com. Would that be a good option for you?

Yeah and it's very easy to implement it so it would be better if you do it on your own in my opinion.

**Comment by reveurguy** [comment]
ok.
